In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("supermarket_sales_case_study.csv")
df.head(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,852-73-6802,A,Yangon,Normal,Female,Health and beauty,52.24,4,10.4480,219.4080,1/1/2023,12:46,Ewallet,208.96,4.761905,10.4480,7.1
1,845-69-3430,A,Yangon,Member,Male,Sports and travel,50.54,6,15.1620,318.4020,1/1/2023,17:55,Ewallet,303.24,4.761905,15.1620,8.4
2,307-57-9082,B,Mandalay,Member,Male,Fashion accessories,69.86,4,13.9720,293.4120,1/1/2023,12:40,Credit card,279.44,4.761905,13.9720,8.3
3,453-35-6332,B,Mandalay,Member,Female,Home and lifestyle,52.63,5,13.1575,276.3075,1/1/2023,17:20,Ewallet,263.15,4.761905,13.1575,7.1
4,365-74-6230,B,Mandalay,Normal,Male,Sports and travel,42.97,4,8.5940,180.4740,1/1/2023,17:36,Cash,171.88,4.761905,8.5940,5.3

In [3]:
rows, columns = df.shape
print(f"Rows: {rows}, Columns: {columns}")

Rows: 8631, Columns: 17

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8631 entries, 0 to 8630
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               8631 non-null   object
 1   Branch                   8631 non-null   object
 2   City                     8631 non-null   object
 3   Customer type            8567 non-null   object
 4   Gender                   8631 non-null   object
 5   Product line             8631 non-null   object
 6   Unit price               8631 non-null   float64
 7   Quantity                 8631 non-null   int64
 8   Tax 5%                   8631 non-null   float64
 9   Total                    8631 non-null   float64
 10  Date                     8614 non-null   object
 11  Time                     8631 non-null   object
 12  Payment                  8631 non-null   object
 13  cogs                     8631 non-null   float64
 14  gross margin percentage  8631 non-null   float64
 15  gross income             8631 non-null   float64
 16  Rating                   8543 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 1.1+ MB

In [5]:
df.isnull().sum()

Invoice ID                  0
Branch                      0
City                        0
Customer type              64
Gender                      0
Product line                0
Unit price                  0
Quantity                    0
Tax 5%                      0
Total                       0
Date                       17
Time                        0
Payment                     0
cogs                        0
gross margin percentage     0
gross income                0
Rating                     88
dtype: int64

In [6]:
df['Customer type'].unique()

array(['Normal', 'Member', nan], dtype=object)

In [7]:
df['Customer type'].fillna("Unknown", inplace=True)

In [8]:
df['Rating'].fillna(df['Rating'].median(), inplace=True)

In [9]:
df.isnull().sum()

Invoice ID                  0
Branch                      0
City                        0
Customer type               0
Gender                      0
Product line                0
Unit price                  0
Quantity                    0
Tax 5%                      0
Total                       0
Date                       17
Time                        0
Payment                     0
cogs                        0
gross margin percentage     0
gross income                0
Rating                      0
dtype: int64

In [10]:
df.dropna(subset='Date', inplace=True)

In [11]:
df.isnull().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

# Fixing Wrong Data Types For Date Columns

In [12]:
df['Date'] = pd.to_datetime(
    df['Date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [13]:
df['Date'].isna().sum()

45

In [14]:
df.dropna(subset='Date', inplace=True)

In [15]:
df['Date'] = pd.to_datetime(df['Date'])

In [16]:
df['Time'] = pd.to_datetime(df['Time'])

C:\Users\Abubakar\AppData\Local\Temp\ipykernel_2312\2145562215.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Time'] = pd.to_datetime(df['Time'])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8569 entries, 0 to 8630
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               8569 non-null   object
 1   Branch                   8569 non-null   object
 2   City                     8569 non-null   object
 3   Customer type            8569 non-null   object
 4   Gender                   8569 non-null   object
 5   Product line             8569 non-null   object
 6   Unit price               8569 non-null   float64
 7   Quantity                 8569 non-null   int64
 8   Tax 5%                   8569 non-null   float64
 9   Total                    8569 non-null   float64
 10  Date                     8569 non-null   datetime64[ns]
 11  Time                     8569 non-null   datetime64[ns]
 12  Payment                  8569 non-null   object
 13  cogs                     8569 non-null   float64
 14  gross margin percentage  8569 non-null   float64
 15  gross income             8569 non-null   float64
 16  Rating                   8569 non-null   float64
dtypes: datetime64[ns](2), float64(7), int64(1), object(7)
memory usage: 1.2+ MB

In [18]:
df['Invoice ID'].value_counts()

Invoice ID
424-25-1084    2
841-20-8135    2
419-17-9296    2
548-21-1136    2
567-24-9303    2
              ..
456-43-3555    1
365-71-8192    1
278-55-6111    1
678-79-4973    1
187-14-9414    1
Name: count, Length: 8514, dtype: int64

In [19]:
df.duplicated().sum()

30

In [20]:
df['Gender'] = df['Gender'].str.strip().str.lower()

In [21]:
df['Gender'].unique()

array(['female', 'male'], dtype=object)

In [22]:
df['Branch'].unique()

array(['A', 'B', 'C'], dtype=object)

In [23]:
df['City'].unique()

array(['Yangon', 'Mandalay', 'Naypyitaw'], dtype=object)

In [24]:
df['Payment'].unique()

array(['Ewallet', 'Credit card', 'Cash', 'cash', ' Credit card',
       'ewallet ', 'EWALLET'], dtype=object)

In [25]:
df['Payment'].str.strip().str.lower().unique()

array(['ewallet', 'credit card', 'cash'], dtype=object)

In [26]:
df['Payment'] = df['Payment'].str.strip().str.lower()

In [27]:
df = df.drop_duplicates(subset='Invoice ID', keep='last')

In [28]:
df.shape

(8514, 17)

In [29]:
df[df['Quantity'] < 0]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
16,284-74-2560,C,Naypyitaw,Member,female,Home and lifestyle,48.32,-5,12.0800,253.6800,2023-02-01,2026-10-23 12:27:00,ewallet,241.60,4.761905,12.0800,5.7
149,715-35-8258,A,Yangon,Normal,female,Food and beverages,25.79,-5,6.4475,135.3975,2023-01-14,2026-10-23 19:48:00,credit card,128.95,4.761905,6.4475,5.2
187,859-85-2834,B,Mandalay,Normal,female,Food and beverages,31.04,-4,6.2080,130.3680,2023-01-17,2026-10-23 19:19:00,cash,124.16,4.761905,6.2080,9.7
533,292-46-4846,C,Naypyitaw,Member,male,Electronic accessories,89.59,-4,17.9180,376.2780,2023-02-14,2026-10-23 15:46:00,credit card,358.36,4.761905,17.9180,9.9
595,487-13-6577,C,Naypyitaw,Member,male,Health and beauty,56.46,-9,25.4070,533.5470,2023-02-19,2026-10-23 17:40:00,ewallet,508.14,4.761905,25.4070,8.4
706,461-15-4496,A,Yangon,Normal,male,Fashion accessories,50.74,-5,12.6850,266.3850,2023-01-03,2026-10-23 17:37:00,cash,253.70,4.761905,12.6850,8.9
769,242-32-1189,A,Yangon,Normal,female,Health and beauty,74.06,-5,18.5150,388.8150,2023-05-03,2026-10-23 12:00:00,ewallet,370.30,4.761905,18.5150,7.4
832,608-62-8786,C,Naypyitaw,Normal,male,Health and beauty,45.11,-5,11.2775,236.8275,2023-10-03,2026-10-23 14:45:00,ewallet,225.55,4.761905,11.2775,8.0
1398,487-57-9215,C,Naypyitaw,Member,female,Food and beverages,19.76,-8,7.9040,165.9840,2023-02-05,2026-10-23 17:23:00,credit card,158.08,4.761905,7.9040,6.0
1691,583-74-2884,C,Naypyitaw,Normal,male,Fashion accessories,71.94,-9,32.3730,679.8330,2023-05-27,2026-10-23 15:50:00,ewallet,647.46,4.761905,32.3730,6.6
1708,384-63-9642,C,Naypyitaw,Normal,female,Health and beauty,32.24,-5,8.0600,169.2600,2023-05-28,2026-10-23 13:32:00,credit card,161.20,4.761905,8.0600,4.9
1994,182-80-8118,A,Yangon,Normal,female,Sports and travel,45.21,-5,11.3025,237.3525,2023-06-23,2026-10-23 17:45:00,cash,226.05,4.761905,11.3025,6.2
2057,667-90-7614,B,Mandalay,Normal,female,Health and beauty,45.74,-8,18.2960,384.2160,2023-06-28,2026-10-23 18:00:00,cash,365.92,4.761905,18.2960,5.1
2161,266-65-1868,C,Naypyitaw,Member,male,Food and beverages,41.87,-9,18.8415,395.6715,2023-08-07,2026-10-23 11:39:00,ewallet,376.83,4.761905,18.8415,8.1
2300,659-76-9562,C,Naypyitaw,Member,male,Sports and travel,78.85,-4,15.7700,331.1700,2023-07-22,2026-10-23 19:51:00,credit card,315.40,4.761905,15.7700,7.0
2387,448-65-2845,C,Naypyitaw,Normal,female,Home and lifestyle,81.25,-5,20.3125,426.5625,2023-07-31,2026-10-23 12:15:00,cash,406.25,4.761905,20.3125,4.0
2775,474-44-4922,C,Naypyitaw,Member,female,Home and lifestyle,41.53,-4,8.3060,174.4260,2023-06-09,2026-10-23 16:46:00,ewallet,166.12,4.761905,8.3060,6.7
3081,686-37-7938,A,Yangon,Normal,male,Home and lifestyle,46.05,-9,20.7225,435.1725,2023-04-10,2026-10-23 12:42:00,cash,414.45,4.761905,20.7225,8.0
3162,242-52-1302,B,Mandalay,Normal,male,Electronic accessories,50.04,-3,7.5060,157.6260,2023-10-10,2026-10-23 12:49:00,cash,150.12,4.761905,7.5060,5.7
3618,508-42-5069,A,Yangon,Normal,male,Home and lifestyle,52.32,-4,10.4640,219.7440,2023-11-11,2026-10-23 20:33:00,cash,209.28,4.761905,10.4640,6.2
3910,203-96-4325,B,Mandalay,Normal,male,Food and beverages,44.24,-5,11.0600,232.2600,2023-02-12,2026-10-23 12:50:00,credit card,221.20,4.761905,11.0600,6.0
4068,139-34-9623,A,Yangon,Member,female,Fashion accessories,86.40,-5,21.6000,453.6000,2023-12-13,2026-10-23 12:08:00,cash,432.00,4.761905,21.6000,7.6
4083,316-87-8619,A,Yangon,Normal,male,Home and lifestyle,73.32,-8,29.3280,615.8880,2023-12-14,2026-10-23 15:59:00,credit card,586.56,4.761905,29.3280,6.8
4133,297-93-5009,B,Mandalay,Normal,female,Fashion accessories,56.27,-4,11.2540,236.3340,2023-12-17,2026-10-23 13:46:00,credit card,225.08,4.761905,11.2540,8.0
4135,694-47-3932,B,Mandalay,Member,male,Food and beverages,32.65,-7,11.4275,239.9775,2023-12-17,2026-10-23 15:03:00,ewallet,228.55,4.761905,11.4275,7.1
4223,803-56-6270,A,Yangon,Normal,male,Fashion accessories,58.34,-4,11.6680,245.0280,2023-12-25,2026-10-23 11:39:00,cash,233.36,4.761905,11.6680,7.6
4309,457-94-8972,B,Mandalay,Member,female,Sports and travel,53.08,-4,10.6160,222.9360,2023-12-30,2026-10-23 15:29:00,credit card,212.32,4.761905,10.6160,7.0
4469,165-34-1588,B,Mandalay,Normal,female,Home and lifestyle,82.90,-4,16.5800,348.1800,2024-11-01,2026-10-23 19:09:00,cash,331.60,4.761905,16.5800,9.3
4536,791-60-7930,C,Naypyitaw,Normal,male,Home and lifestyle,36.70,-4,7.3400,154.1400,2024-01-16,2026-10-23 17:11:00,cash,146.80,4.761905,7.3400,6.1
4679,113-41-2374,C,Naypyitaw,Member,male,Fashion accessories,51.81,-8,20.7240,435.2040,2024-01-29,2026-10-23 18:13:00,cash,414.48,4.761905,20.7240,5.5
4975,216-17-7486,B,Mandalay,Member,male,Home and lifestyle,48.08,-4,9.6160,201.9360,2024-02-24,2026-10-23 15:37:00,ewallet,192.32,4.761905,9.6160,8.4
5259,762-43-4318,C,Naypyitaw,Member,male,Food and beverages,38.44,-7,13.4540,282.5340,2024-03-18,2026-10-23 12:23:00,cash,269.08,4.761905,13.4540,9.2
5287,397-67-1080,C,Naypyitaw,Normal,male,Sports and travel,61.51,-3,9.2265,193.7565,2024-03-21,2026-10-23 17:00:00,ewallet,184.53,4.761905,9.2265,9.8
5358,156-24-8551,B,Mandalay,Member,female,Fashion accessories,48.20,-4,9.6400,202.4400,2024-03-27,2026-10-23 12:06:00,ewallet,192.80,4.761905,9.6400,8.8
5679,678-50-3182,C,Naypyitaw,Normal,female,Home and lifestyle,57.08,-3,8.5620,179.8020,2024-04-29,2026-10-23 13:28:00,cash,171.24,4.761905,8.5620,8.2
5757,831-88-3704,B,Mandalay,Member,female,Home and lifestyle,50.71,-6,15.2130,319.4730,2024-06-05,2026-10-23 12:15:00,ewallet,304.26,4.761905,15.2130,6.9
5941,397-24-2823,B,Mandalay,Member,female,Home and lifestyle,59.33,-4,11.8660,249.1860,2024-05-23,2026-10-23 18:58:00,credit card,237.32,4.761905,11.8660,7.6
6002,524-96-7061,A,Yangon,Normal,female,Food and beverages,23.42,-5,5.8550,122.9550,2024-05-29,2026-10-23 11:24:00,credit card,117.10,4.761905,5.8550,6.8
6018,878-19-1547,A,Yangon,Normal,female,Electronic accessories,80.47,-5,20.1175,422.4675,2024-05-30,2026-10-23 17:09:00,ewallet,402.35,4.761905,20.1175,4.0
6127,434-39-1150,B,Mandalay,Normal,male,Home and lifestyle,65.62,-7,22.9670,482.3070,2024-09-06,2026-10-23 17:40:00,ewallet,459.34,4.761905,22.9670,6.0
6235,878-57-4863,C,Naypyitaw,Member,female,Electronic accessories,80.07,-4,16.0140,336.2940,2024-06-22,2026-10-23 13:55:00,ewallet,320.28,4.761905,16.0140,6.4
6502,618-57-9987,C,Naypyitaw,Normal,female,Electronic accessories,94.57,-7,33.0995,695.0895,2024-07-18,2026-10-23 15:12:00,credit card,661.99,4.761905,33.0995,7.8
6539,477-75-5794,B,Mandalay,Normal,female,Food and beverages,48.97,-5,12.2425,257.0925,2024-07-23,2026-10-23 13:03:00,ewallet,244.85,4.761905,12.2425,9.6
6557,889-17-8722,C,Naypyitaw,Normal,male,Home and lifestyle,68.67,-8,27.4680,576.8280,2024-07-24,2026-10-23 20:07:00,ewallet,549.36,4.761905,27.4680,7.1
6566,675-13-3544,A,Yangon,Normal,male,Home and lifestyle,54.71,-5,13.6775,287.2275,2024-07-26,2026-10-23 15:37:00,cash,273.55,4.761905,13.6775,7.3
6962,420-21-8607,A,Yangon,Member,female,Home and lifestyle,56.89,-4,11.3780,238.9380,2024-03-09,2026-10-23 13:24:00,credit card,227.56,4.761905,11.3780,9.3
7098,778-12-8501,A,Yangon,Member,male,Food and beverages,36.85,-7,12.8975,270.8475,2024-09-15,2026-10-23 17:58:00,credit card,257.95,4.761905,12.8975,8.0
7263,788-89-5308,C,Naypyitaw,Member,male,Health and beauty,48.75,-3,7.3125,153.5625,2024-09-29,2026-10-23 14:47:00,ewallet,146.25,4.761905,7.3125,7.7
7387,617-50-3444,B,Mandalay,Member,female,Electronic accessories,37.18,-3,5.5770,117.1170,2024-09-10,2026-10-23 19:46:00,ewallet,111.54,4.761905,5.5770,10.0
7501,775-14-6334,C,Naypyitaw,Member,female,Health and beauty,28.74,-4,5.7480,120.7080,2024-10-17,2026-10-23 12:23:00,ewallet,114.96,4.761905,5.7480,6.5
7530,457-73-5659,B,Mandalay,Member,female,Fashion accessories,40.34,-5,10.0850,211.7850,2024-10-19,2026-10-23 16:05:00,ewallet,201.70,4.761905,10.0850,8.2
7646,620-48-4134,B,Mandalay,Member,female,Sports and travel,51.00,-5,12.7500,267.7500,2024-10-28,2026-10-23 16:29:00,credit card,255.00,4.761905,12.7500,6.4
7650,223-70-9410,A,Yangon,Normal,female,Electronic accessories,101.83,-2,10.1830,213.8430,2024-10-29,2026-10-23 11:19:00,credit card,203.66,4.761905,10.1830,6.2
7829,272-93-6070,C,Naypyitaw,Normal,female,Electronic accessories,45.02,-5,11.2550,236.3550,2024-09-11,2026-10-23 17:35:00,credit card,225.10,4.761905,11.2550,8.2
7883,753-95-2096,B,Mandalay,Member,female,Electronic accessories,83.02,-6,24.9060,523.0260,2024-11-14,2026-10-23 15:19:00,credit card,498.12,4.761905,24.9060,6.9
7921,188-71-3104,C,Naypyitaw,Normal,male,Fashion accessories,46.67,-4,9.3340,196.0140,2024-11-17,2026-10-23 17:42:00,cash,186.68,4.761905,9.3340,6.7
7954,404-95-4985,C,Naypyitaw,Member,male,Sports and travel,41.02,-8,16.4080,344.5680,2024-11-20,2026-10-23 12:53:00,cash,328.16,4.761905,16.4080,6.1

In [30]:
df['Quantity'] = abs(df['Quantity'])

In [31]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,852-73-6802,A,Yangon,Normal,female,Health and beauty,52.24,4,10.4480,219.4080,2023-01-01,2026-10-23 12:46:00,ewallet,208.96,4.761905,10.4480,7.1
1,845-69-3430,A,Yangon,Member,male,Sports and travel,50.54,6,15.1620,318.4020,2023-01-01,2026-10-23 17:55:00,ewallet,303.24,4.761905,15.1620,8.4
2,307-57-9082,B,Mandalay,Member,male,Fashion accessories,69.86,4,13.9720,293.4120,2023-01-01,2026-10-23 12:40:00,credit card,279.44,4.761905,13.9720,8.3
3,453-35-6332,B,Mandalay,Member,female,Home and lifestyle,52.63,5,13.1575,276.3075,2023-01-01,2026-10-23 17:20:00,ewallet,263.15,4.761905,13.1575,7.1
4,365-74-6230,B,Mandalay,Normal,male,Sports and travel,42.97,4,8.5940,180.4740,2023-01-01,2026-10-23 17:36:00,cash,171.88,4.761905,8.5940,5.3

In [32]:
df['Quantity'] * df['Unit price'] * 1.05

0       219.4080
1       318.4020
2       293.4120
3       276.3075
4       180.4740
          ...
8626    137.8020
8627    665.1120
8628    260.5050
8629    375.2175
8630    376.9500
Length: 8514, dtype: float64

# Answering The Briefs

### 1. Adding Date Columns

In [33]:
df['Year'] = df['Date'].dt.year

In [34]:
df['Quarter'] = df['Year'].astype(str) + "Q" + df['Date'].dt.quarter.astype(str)

In [35]:
df['Day'] = df['Date'].dt.day_name()

In [36]:
df['Hour'] = df['Time'].dt.hour

In [37]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,...,Time,Payment,cogs,gross margin percentage,gross income,Rating,Year,Quarter,Day,Hour
0,852-73-6802,A,Yangon,Normal,female,Health and beauty,52.24,4,10.4480,219.4080,...,2026-10-23 12:46:00,ewallet,208.96,4.761905,10.4480,7.1,2023,2023Q1,Sunday,12
1,845-69-3430,A,Yangon,Member,male,Sports and travel,50.54,6,15.1620,318.4020,...,2026-10-23 17:55:00,ewallet,303.24,4.761905,15.1620,8.4,2023,2023Q1,Sunday,17
2,307-57-9082,B,Mandalay,Member,male,Fashion accessories,69.86,4,13.9720,293.4120,...,2026-10-23 12:40:00,credit card,279.44,4.761905,13.9720,8.3,2023,2023Q1,Sunday,12
3,453-35-6332,B,Mandalay,Member,female,Home and lifestyle,52.63,5,13.1575,276.3075,...,2026-10-23 17:20:00,ewallet,263.15,4.761905,13.1575,7.1,2023,2023Q1,Sunday,17
4,365-74-6230,B,Mandalay,Normal,male,Sports and travel,42.97,4,8.5940,180.4740,...,2026-10-23 17:36:00,cash,171.88,4.761905,8.5940,5.3,2023,2023Q1,Sunday,17

## 2. Bucketing the trading day

In [38]:
df['Parts of Day'] = df['Hour'].apply(lambda x: "Morning" if 10 <= x < 13
                else "Afternoon" if 13 <= x < 17
                else "Evening" if 17 <= x < 21
                else "Invalid")

In [46]:
df.head(1)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,...,Payment,cogs,gross margin percentage,gross income,Rating,Year,Quarter,Day,Hour,Parts of Day
0,852-73-6802,A,Yangon,Normal,female,Health and beauty,52.24,4,10.448,219.408,...,ewallet,208.96,4.761905,10.448,7.1,2023,2023Q1,Sunday,12,Morning

In [47]:
df['Parts of Day'].value_counts()

Parts of Day
Evening      3409
Afternoon    2953
Morning      2152
Name: count, dtype: int64

In [59]:
counts = df['Parts of Day'].value_counts()

transactions_per_hour = counts / pd.Series({
    'Morning': 3,
    'Afternoon': 4,
    'Evening': 4
})

print("Transactions per Hour")
print("-"*30)
print(transactions_per_hour)

Transactions per Hour
------------------------------
Afternoon    738.250000
Evening      852.250000
Morning      717.333333
dtype: float64

### 3. Compare against target

In [70]:
small_targets = pd.DataFrame(df.groupby(['Branch', 'Quarter'])['Total'].sum())
small_targets

                      Total
Branch Quarter
A      2023Q1   109259.6870
       2023Q2    90705.8700
       2023Q3    96636.2565
       2023Q4   118054.9175
       2024Q1   111057.4810
       2024Q2   106278.0840
       2024Q3    96559.1800
       2024Q4   103878.5315
B      2023Q1    94557.1925
       2023Q2    98096.5590
       2023Q3    84948.4115
       2023Q4   106915.4850
       2024Q1    92736.9620
       2024Q2    76619.3395
       2024Q3    88370.8455
       2024Q4   105498.1555
C      2023Q1    98700.2435
       2023Q2    94791.2045
       2023Q3    85961.3725
       2023Q4   119007.0730
       2024Q1   111591.7210
       2024Q2    95894.5835
       2024Q3    96988.5700
       2024Q4   126408.8810

In [64]:
target = 100000

### Variance

In [72]:
small_targets['Variance'] = (df.groupby(['Branch', 'Quarter'])['Total'].sum()) - target
small_targets

                      Total    Variance
Branch Quarter
A      2023Q1   109259.6870   9259.6870
       2023Q2    90705.8700  -9294.1300
       2023Q3    96636.2565  -3363.7435
       2023Q4   118054.9175  18054.9175
       2024Q1   111057.4810  11057.4810
       2024Q2   106278.0840   6278.0840
       2024Q3    96559.1800  -3440.8200
       2024Q4   103878.5315   3878.5315
B      2023Q1    94557.1925  -5442.8075
       2023Q2    98096.5590  -1903.4410
       2023Q3    84948.4115 -15051.5885
       2023Q4   106915.4850   6915.4850
       2024Q1    92736.9620  -7263.0380
       2024Q2    76619.3395 -23380.6605
       2024Q3    88370.8455 -11629.1545
       2024Q4   105498.1555   5498.1555
C      2023Q1    98700.2435  -1299.7565
       2023Q2    94791.2045  -5208.7955
       2023Q3    85961.3725 -14038.6275
       2023Q4   119007.0730  19007.0730
       2024Q1   111591.7210  11591.7210
       2024Q2    95894.5835  -4105.4165
       2024Q3    96988.5700  -3011.4300
       2024Q4   126408.8810  26408.8810

### Percentage of Target

In [78]:
small_targets['Percentage of target'] = ((df.groupby(['Branch', 'Quarter'])['Total'].sum())/target)*100
small_targets['Hit'] = per_of_target.apply(lambda x: "Yes" if x >= 100 else "No")
small_targets

                      Total    Variance  Percentage of target  Hit
Branch Quarter
A      2023Q1   109259.6870   9259.6870            109.259687  Yes
       2023Q2    90705.8700  -9294.1300             90.705870   No
       2023Q3    96636.2565  -3363.7435             96.636257   No
       2023Q4   118054.9175  18054.9175            118.054917  Yes
       2024Q1   111057.4810  11057.4810            111.057481  Yes
       2024Q2   106278.0840   6278.0840            106.278084  Yes
       2024Q3    96559.1800  -3440.8200             96.559180   No
       2024Q4   103878.5315   3878.5315            103.878531  Yes
B      2023Q1    94557.1925  -5442.8075             94.557193   No
       2023Q2    98096.5590  -1903.4410             98.096559   No
       2023Q3    84948.4115 -15051.5885             84.948411   No
       2023Q4   106915.4850   6915.4850            106.915485  Yes
       2024Q1    92736.9620  -7263.0380             92.736962   No
       2024Q2    76619.3395 -23380.6605             76.619340   No
       2024Q3    88370.8455 -11629.1545             88.370846   No
       2024Q4   105498.1555   5498.1555            105.498155  Yes
C      2023Q1    98700.2435  -1299.7565             98.700243   No
       2023Q2    94791.2045  -5208.7955             94.791205   No
       2023Q3    85961.3725 -14038.6275             85.961372   No
       2023Q4   119007.0730  19007.0730            119.007073  Yes
       2024Q1   111591.7210  11591.7210            111.591721  Yes
       2024Q2    95894.5835  -4105.4165             95.894583   No
       2024Q3    96988.5700  -3011.4300             96.988570   No
       2024Q4   126408.8810  26408.8810            126.408881  Yes

# Summarise Each Branch

### Average quarterly revenue

In [79]:
small_targets.groupby('Branch')['Total'].mean()

Branch
A    104053.750937
B     93467.868813
C    103667.956125
Name: Total, dtype: float64

In [96]:
df.head(1)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,...,Payment,cogs,gross margin percentage,gross income,Rating,Year,Quarter,Day,Hour,Parts of Day
0,852-73-6802,A,Yangon,Normal,female,Health and beauty,52.24,4,10.448,219.408,...,ewallet,208.96,4.761905,10.448,7.1,2023,2023Q1,Sunday,12,Morning

# Busy Times

In [100]:
transaction_in_a_day = df['Day'].value_counts()
no_of_weekdays = df.groupby('Day')['Date'].nunique()

In [104]:
daily_avg_transaction = transaction_in_a_day / no_of_weekdays
daily_avg_transaction

Day
Friday       12.456311
Monday        9.903846
Saturday     13.617647
Sunday       13.737864
Thursday     11.058252
Tuesday      11.144231
Wednesday    10.567308
dtype: float64

In [113]:
transaction_in_hour = df['Hour'].value_counts()
no_of_hours = df.groupby('Hour')['Date'].nunique()
transaction_in_hour, no_of_hours

(Hour
 18    1165
 12    1098
 17    1003
 13     903
 19     846
 16     722
 14     670
 11     663
 15     658
 20     395
 10     391
 Name: count, dtype: int64,
 Hour
 10    298
 11    412
 12    558
 13    506
 14    396
 15    416
 16    442
 17    528
 18    567
 19    480
 20    292
 Name: Date, dtype: int64)

In [115]:
hourly_avg_transaction = transaction_in_hour / no_of_hours
hourly_avg_transaction.sort_values(ascending=False)

Hour
18    2.054674
12    1.967742
17    1.899621
13    1.784585
19    1.762500
14    1.691919
16    1.633484
11    1.609223
15    1.581731
20    1.352740
10    1.312081
dtype: float64

In [ ]:
pd.to